# docker-compose.yml

services:
  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    networks:
      - app-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
